# Generated by Django 5.1.7 on 2025-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_postgre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('maintenance', 'Wartung'), ('error', 'Fehler')], default='active', max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
